/*
Taikun - WebApi

Testing ProjectAppParamsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/kibernetik542/baburgo"
)

func Test_openapi_ProjectAppParamsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ProjectAppParamsApiService ProjectappparamEdit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectAppId int32

		httpRes, err := apiClient.ProjectAppParamsApi.ProjectappparamEdit(context.Background(), projectAppId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
